### ISSUE TITLE
python 3.8 wheel packaging

### ISSUE THREAD

**Issue by kapilt** [wasmerio/python-ext-wasm#105]
Thanks for proposing a new feature!

### Motivation
currently installing wasmer on python 3.8 results in a empty package installation

```python
>>> import wasmer                                            
Traceback (most recent call last):                        
  File "<stdin>", line 1, in <module>                             
  File "/Users/kapilt/.pyenv/versions/pywasm/lib/python3.8/site-packages/wasmer/__init__.py", line 1, in <module>
    raise ImportError("Wasmer is not available on this system")
ImportError: Wasmer is not available on this system
```

### Proposed solution

updating the build / release to use python 3.8 for artifacts published would resolve.

**Comment by kapilt** [comment]
while compiling this package it looks like 3.8 is already in the justfile for publishing, so just waiting on a release.

**Comment by Hywan** [comment]
The extension doesn't compile for Python 3.8 on the CI yet. Give me some days.

**Comment by Hywan** [comment]
pyo3 doesn't support Python 3.8 on Azure CI (so Github Actions), https://github.com/PyO3/pyo3/issues/704, which is blocking for the moment.

**Comment by Hywan** [comment]
Latest release provides 3.8 wheels, https://pypi.org/project/wasmer/#files.
