### ISSUE TITLE
support providing imports / host functions

### ISSUE THREAD

**Issue by kapilt** [wasmerio/python-ext-wasm#106]
Thanks for proposing a new feature!

### Motivation

I was trying to run a wasm file generated by https://github.com/open-policy-agent/opa

```
>>> i = Instance(wasm_bytes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Failed to instantiate the module:
    7 link errors: (1 of 7) Import not found, namespace: env, name: opa_abort (2 of 7) Import not found, namespace: env, name: opa_builtin0 (3 of 7) Import not found, namespace: env, name: opa_builtin1 (4 of 7) Import not found, namespace: env, name: opa_builtin2 (5 of 7) Import not found, namespace: env, name: opa_builtin3 (6 of 7) Import not found, namespace: env, name: opa_builtin4 (7 of 7) Import not found, namespace: env, name: memory
```

it looks like opa expects as part of its integration to provider some imports, here's an example in js

https://github.com/open-policy-agent/npm-opa-wasm/blob/master/src/opa.js#L95

### Proposed solution

allow the user to pass in an imports mapping

at the moment it looks as though that its always set to an empty import object

```rust
        let imports = imports! {};

        // Instantiate the module.
        let instance = match self.module.instantiate(&imports) {
```

**Comment by kapilt** [comment]
looks like this is a duplicate of #28 

although i'll note this two things.

1.  there are other wasmer dynamically typed languages with support (php ) https://github.com/wasmerio/php-ext-wasm/blob/master/src/wasm.cc#L683

2. the usage here also wants to pass a wasm memory instance in addition to host functions via import.

**Comment by Hywan** [comment]
Closing as it's a duplication of #28. We are working on it. It requires a new API in `wasmer-runtime-core`, and we are working on it :-). Thanks for your patience!
