### ISSUE TITLE
AttributeError: 'Module' object has no attribute 'custom_section_names'

### ISSUE THREAD

**Issue by caspervonb** [wasmerio/python-ext-wasm#124]
Is the pip release out of sync with the README or something? 

The following fails with a fresh install from pip on python 3.7, same goes with just about anything except the Module and Instance constructor;
```python
from wasmer import Module

wasm_bytes = open('a.out', 'rb').read()
wasm_module = Module(wasm_bytes)
print(wasm_module.custom_section_names)
```

**Comment by Hywan** [comment]
Yeah, the `README.md` is for the `master` branch. You can expect a release soon.

**Comment by Hywan** [comment]
The new release contains the custom section API. Closing this issue.
