### ISSUE TITLE
ImportError: Wasmer is not available on this system

### ISSUE THREAD

**Issue by KristoferHansson** [wasmerio/python-ext-wasm#126]
### Describe the bug

Trying to install and use wasmer in windows 10, using (mini)conda environment with py3.7(tried with 3.8 and 3.6 also), installed wasmer "successfully" via: pip install wasmer

First import fails with the following output:

> (py37) C:\tmp>python test_wasm.py
> Traceback (most recent call last):
>   File "test_wasm.py", line 1, in <module>
>     from wasmer import Instance
>   File "C:\Users\kha\AppData\Local\Continuum\miniconda3\envs\py37\lib\site-packages\wasmer\__init__.py", line 1, in <module>
>     raise ImportError("Wasmer is not available on this system")
> ImportError: Wasmer is not available on this system
> 

**NOTE:** Exact same procedure works fine when performed in a WSL(1) Ubuntu instance on the same machine

**Comment by Hywan** [comment]
We don't support Windows yet. Please subscribe to #100 or #29.
