### ISSUE TITLE
Unable to find attribute 'exports'

### ISSUE THREAD

**Issue by extraymond** [wasmerio/python-ext-wasm#13]
Hi! I've tried running the example to see how wasmer runs, and encountered the error:
```'libwasmer.Instance' object has no attribute 'exports'```

wasmer: 0.1.4
python: 3.7.3
wasm: build with cargo wasm.

The wasm files seems working when I load it with the below code:

```js
fetch('rusty.wasm').then(response =>
        response.arrayBuffer()
      ).then(bytes =>
        WebAssembly.instantiate(bytes, {})
      ).then(results => {
        alert(results.instance.exports.add_one(41));
      });
```

**Comment by Hywan** [comment]
Hi!

It's coming in the next version. It's on the `master` right now. I'm likely to publish a new version this week.

If the 0.1.4 version, you have to write `instance.call('add_one', [Value.i32(41)]`.

**Comment by Hywan** [comment]
Version 0.2.0 released.
