### ISSUE TITLE
Publish the any wheel

### ISSUE THREAD

**Issue by ganwell** [wasmerio/python-ext-wasm#151]
### Summary

In PR #62 a wheel was created that installs anywhere and fails on import. It was published with version 0.3 but not with version 0.4.1. This breaks @syrusakbary snapshottest for me. Could please publish that wheel? It seems that code needed to build the wheel is still there.

**Comment by Hywan** [comment]
Hello,

Thanks for the heads up. Indeed, something has changed during our migration from CircleCI to Github Actions. The `wasmer-any` wheel is now published for wasmer 0.4.1, check https://pypi.org/project/wasmer/0.4.1/#files. I'll update the release script.
