### ISSUE TITLE
ImportError: cannot import name 'Instance' from 'wasmer'

### ISSUE THREAD

**Issue by yazdian** [wasmerio/python-ext-wasm#172]
I'm totally new to wasmer and python but I need to use them anyway.
So I installed python-ext-wasm using "pip3 install wasmer" on macOs and CentOs
I'm using python 3.6 on both
when I try to run my code I get this error :
ImportError: cannot import name 'Instance' from 'wasmer'

**Comment by syrusakbary** [comment]
Can you post here the code you are using so we can debug further?

**Comment by yazdian** [comment]
This is the whole code : 

`from wasmer import Instance

# Get the Wasm module as bytes.
wasm_bytes = open('hash.wasm', 'rb').read()

# Instantiate the Wasm module.
t = Instance(wasm_bytes)
stringToHash = 'abcd'
strLength = len(stringToHash)
pointer = t.b(strLength)
memory8 = instance.memory.uint8_view()

# put to memory
step = 0
for char in stringToHash :
    memory8[pointer + step] = ord(char)
    step += 1
    
t.d(8, pointer, strLength)

memory32 = instance.memory.int32_view()

pointer2 = memory32[2]
len2 = memory32[3]
result = bytes(memory8[pointer2:pointer2+len2]).decode()

print(result)`

and this is the error I get : 
`Traceback (most recent call last):
  File "wasmer.py", line 1, in <module>
    from wasmer import Instance
  File "/wasmer.py", line 1, in <module>
    from wasmer import Instance
ImportError: cannot import name 'Instance' from 'wasmer'`

**Comment by Urhengulas** [comment]
The problem is, that your file is called `wasmer.py`.
Since you are running:
```python
from wasmer import Instance
```
and your file is called `wasmer.py`, python tries to import `Instance` from this particular file.

### fix
Just rename your file `wasmer.py` (e.g. `hash.py`) and it should work.

This problem isn't related to the `wasmer` library, but is just normal python import confusion :sweat_smile:

**Comment by yazdian** [comment]
Thank you so much,
As I mentioned earlier I'm new to python and I didn't know that.
