### ISSUE TITLE
WASI support

### ISSUE THREAD

**Issue by whitequark** [wasmerio/python-ext-wasm#191]
### Motivation

I'd like to be able to (easily) use WASI with Wasmer's Python package in order to publish a native dependency of my application on PyPI. Wasmtime-py, which is what I'm currently using, does provide this.

### Proposed solution

Expose WASI functions (perhaps from wasi-common?) through the Python interface in a way that allows easily linking them to WASM modules.

### Additional context

The dependency I'm packaging is [here](https://github.com/nmigen/nmigen-yosys).

**Comment by Hywan** [comment]
Closed by #167.

The `README.md` contains all the documentation you need I guess. A new release will come soon.

**Comment by whitequark** [comment]
Thanks!

**Comment by Hywan** [comment]
You're welcome :-)
