### ISSUE TITLE
Typo: README.md: `assert bytes(memory_view[0:3]).decode() == 'Wasmer'`

### ISSUE THREAD

**Issue by kk49** [wasmerio/python-ext-wasm#206]
At https://github.com/wasmerio/python-ext-wasm#getting-an-access-to-the-in-memory-data

`assert bytes(memory_view[0:3]).decode() == 'Wasmer'`

should be
`assert bytes(memory_view[0:6]).decode() == 'Wasmer'`

**Comment by Hywan** [comment]
You're right!
