### ISSUE TITLE
Include a wasm compile option ?

### ISSUE THREAD

**Issue by stonebig** [wasmerio/python-ext-wasm#24]
Would it be possible tp include a wasm compiler option like project https://bitbucket.org/windel/ppci ?

**Comment by Hywan** [comment]
Hello,

Can you be more precise about your question please? What options would you like to see?

**Comment by stonebig** [comment]
well, maybe I mistaken. At first I would like to do "pip install wasmer" on windows, but there is no Windows wheel. Is it possible ? How do I build it ?

**Comment by Hywan** [comment]
We should definitely add wheels for Windows.

Until that time, if you want to install the extension, you can follow the [Development Section](https://github.com/wasmerio/python-ext-wasm#development). Did you try it already?

**Comment by stonebig** [comment]
Was a bit complex to me, so waited for further motivation to plunge in it.

**Comment by Hywan** [comment]
Sure. I'll keep you informed as soon as we have Windows wheels :-).

**Comment by pannous** [comment]
To come back to the original question:  
Would you consider merging a wasm compilers like:  
https://github.com/almarklein/wasmfun  
https://ppci.readthedocs.io/en/latest/reference/wasm.html  
so that we can do ast manipulations like:  
```
module=wasmer.read('test.wasm')
module.add(wasmer.function(...))
module.save('test.wasm')
```

**Comment by Hywan** [comment]
It's not in our immediate plan, but rather on a longer plan, yes.
