### ISSUE TITLE
Support imported functions

### ISSUE THREAD

**Issue by turbolent** [wasmerio/python-ext-wasm#28]
Does this library support importing Python functions into the WebAssembly module instances? 

I couldn't find any example and looking at the code at https://github.com/wasmerio/python-ext-wasm/blob/89cecbbd672023f2b12ae183641fba2f9cc4c7e3/src/instance.rs#L133-L134 it seems like it is not supported yet?

**Comment by Hywan** [comment]
Hi,

Not yet. We are working on it. The Wasmer runtime API, with its C and C++ bindings, support that but for statically typed languages. We have to make it compliant with dynamically typed languages.

**Comment by filips123** [comment]
@Hywan Is there any update? This is already supported in Go version of Wasmer library.

**Comment by Hywan** [comment]
It's easier in Go than it is with Python. I'm working on it at the runtime-core level, see https://github.com/wasmerio/wasmer/pull/882. It's a WIP.

**Comment by filips123** [comment]
@Hywan Great!When do you expect to be finished?

**Comment by Hywan** [comment]
I can't specify any date :-).

**Comment by sffc** [comment]
Would like to see this feature.  I'm trying to port a Rust module compiled with `wasm_bindgen` to run on Python but am getting "Failed to instantiate the module" errors since there are no function imports available.

**Comment by Hywan** [comment]
Yup, working on it :-).

**Comment by dholth** [comment]
Still going?

**Comment by Hywan** [comment]
Yes, https://github.com/wasmerio/python-ext-wasm/pull/140 is under review.
