### ISSUE TITLE
Add wheels for Windows

### ISSUE THREAD

**Issue by Hywan** [wasmerio/python-ext-wasm#29]
The project publishes wheels for macOS and Linux. We must add wheels for Windows too, as requested in https://github.com/wasmerio/python-ext-wasm/issues/24.

cc @xmclark

**Comment by Mec-iS** [comment]
If I understood correctly, now with [`pyo3-pack build`](https://github.com/PyO3/pyo3-pack#usage) should be pretty straightforward to build wheels for Windows

**Comment by Hywan** [comment]
Yes. The only required step is to migrate from CircleCI to Azure Pipelines.

**Comment by filips123** [comment]
@Hywan Is here also any update? Wheels for Windows should really be needed as it is currently very hard to use this on Windows.

**Comment by Hywan** [comment]
I've to migrate from CircleCI to Azure. I can focus on that next weeks.

**Comment by filips123** [comment]
@Hywan Have you done anything?

**Comment by Hywan** [comment]
We need to configure Azure CI properly, and that will be fast after that. Working on it.

**Comment by filips123** [comment]
As #100 is now merged, does this mean that Windows will be supported in next release?

**Comment by Hywan** [comment]
Correct!

**Comment by Hywan** [comment]
Let's wait for the next release :-).
