### ISSUE TITLE
Provide wasmer core version in resulting Python object

### ISSUE THREAD

**Issue by Mec-iS** [wasmerio/python-ext-wasm#41]
### Motivation

As done in #27 for `__version__` method, it can be useful to have a `__core_version__` method that returns the `wasmer_runtime` version. 

### Proposed solution

I don't know exactly if there is another way of doing introspection into linked libraries (I suppose not due to mangling), the only solution I can imagine is to parse `Cargo.toml` using `toml` crate and then read the `wasmer_runtime` values. Any better way?

### Additional context

We should put as much "meta-information" as possible about the WASM environment in the resulting Python object.

**Comment by Hywan** [comment]
Thanks for the proposal!

Before trying to find a technical solution, I wonder why a Python user could need that information? Any usecase? I think having the extension/library version is a requirement, but I don't see an example where the runtime version can be useful for something. Any help?

**Comment by Mec-iS** [comment]
This may be useful for giving a context to the Python runtime, so user interested can do some introspection in the underlying stack. In my case it is useful as I am trying different functions executions on different library versions.
