### ISSUE TITLE
` ExportedFunction` to ease introspection

### ISSUE THREAD

**Issue by Mec-iS** [wasmerio/python-ext-wasm#68]
The `__call__` method in `ExportedFunction` should be factorised into methods (similar to getters?).

### Motivation

This is important as when debugging Wasmer functions on the Python side there are no introspection tools. So to allow better fine-grained access to information in `wasmer_runtime_core::instance::dyn_func` underlying the exported function, like signature parameters etc. Developers may need to know how `wasmer_runtime_core::instance::ExportedFunction` represent Python function's signature in a way similar to what [Python's inspect module](https://github.com/python/cpython/blob/master/Lib/inspect.py) provides. Also having a `help` method that prints this information on the Python side could be very useful. 

### Proposed solution

I am preparing a PR to implement methods like:
```rust
// returns the dynamic function object. To be used by __call__ and other methods
fn get_runtime_func_obj(&self) -> Result<DynFunc, PyErr> {...}

// other convenience methods
fn get_runtime_signature(&self) -> ... {...}
fn get_runtime_arguments(&self) -> ... {...}
...

// Plus any code required to turn the return values into pyo3 PyObject

```

Please provide feedback.

**Comment by Mec-iS** [comment]
#71

**Comment by Hywan** [comment]
Can you point to me what methods must be implemented in https://docs.python.org/3/library/inspect.html to get a nice Python experience?

**Comment by Mec-iS** [comment]
For now #71 provided the ones I needed. Which ones we may need in future is hard to say, beside the `inspect` module, I will take a look to the most important modules in the stdlib and check out the ones could be critucal to have.

**Comment by Hywan** [comment]
:+1:
