### ISSUE TITLE
Provide built-ins to access memory views

### ISSUE THREAD

**Issue by Mec-iS** [wasmerio/python-ext-wasm#74]
# Motivation

Beside the exported functions (the custom functions written by the user and compiled to Wasm), we  should provide built-in functions that provide a "mini standard library" for the user to leverage on the Python side. For example, regarding this issue, some functions to handle memory views should be included in the Python interface to allow reading/writing to memory views.

### Proposed solution
At the moment I use [these utilities](https://github.com/Mec-iS/rust-wasm-python-101/blob/a5a21420542474f3d665400b30b75f18946a5a48/pywasm/src/memviews.py#L2) to access memory views from my Python scripts:
```python
def get_memory_view(instance, size=8):
    """Get a view of `size` from a Wasmer an instance.
    Returns a memory view"""
    mem = instance.memory
    funcname = f'uint{size}_view'
    return getattr(mem, funcname)()

def write_to_view(bytestr, mem_view, offset=0):
    """Fill memory with values from a bytestring starting at `offset`.
    Returns a memory view"""
    for i, c in enumerate(bytestr):
        mem_view[offset + i] = c
    return mem_view
```
These should be embedded on the Rust side with `pyo3` in the Wasmer Instance, so the user can leverage them as he/she leverages `exports`. So as we have
```python
from instance.exports import some_custom_function
```
we should have something like:
```python
from instance.builtins import get_memory_view
```
To achieve this we can add to `Instance`:
```rust
#[pyclass]
pub struct Instance {
    pub(crate) exports: Py<ExportedFunctions>,
    pub(crate) memory: Py<Memory>,
    // to be added
    pub(crate) builtins: Py<BuiltIns>,   
}
...
#[pyclass]
pub struct BuiltIns {
    pub(crate) instance: Rc<runtime::Instance>,
}

#[pymethods]
impl BuiltIns {
    #[getter]
    fn get_memory_view ...

    #[setter]
    fn write_memory_view ...
}

```

### Additional context

As a reference, see what is already present in [`examples/greet.rs`](https://github.com/wasmerio/python-ext-wasm/blob/1cc08c519292d380847a34b16925935d156de031/examples/greet.rs#L1) for the host machine. This feature proposes to have those functions also for the Wasm Instance as built-ins. 

In addition, as a note, similar to this feature we may want to have a "toolkit" of Rust functions that collects this kind of utilities (as the one in `examples/greet.rs`; C FFI and similar) and provide them in some sort of `wasmer-dev-toolkit` crate.

**Comment by Hywan** [comment]
Hello,

I don't understand the benefits of `get_memory_view(instance, 8)` compared to `instance.memory.uint8_view`? Why one is better than the other?

All memory buffers implement the mapping protocol. We can also implement the buffer protocol if it is necessay. I think it's better to integrate within Python built-ins, rather than providing new libraries on top of that. Thoughts?

Also, with WIT (WebAssembly Interface Types), the user might have to only deal with exported and imported functions only most of the time. This is a feature that will land in a short-time.

**Comment by Mec-iS** [comment]
you are probably right, I was maybe overthinking it. I will take a look to alternatives

**Comment by Mec-iS** [comment]
i was thinking about something like the functionalities in `wasm-python-api` (that I just noted). Is there a reason why we are coding a Python interface while we could code it in `pyo3`.  What are the guidelines for the scope of the two repos?

**Comment by Hywan** [comment]
[wasm-python-api](https://github.com/wasmerio/wasm-python-api) and [wasm-php-api](https://github.com/wasmerio/wasm-php-api) are drafts to get a WebAssembly standard API for Python and PHP, so that tools/developers can be runtime-agnostic.

**Comment by Hywan** [comment]
See https://github.com/WebAssembly/design/issues/1290 for more inputs.
