### ISSUE TITLE
Possibility to call native ctype library code from python-ext-wasm

### ISSUE THREAD

**Issue by jviereck** [wasmerio/python-ext-wasm#81]
### Summary

Assume there is a function foo, which is exposed to python via loading a native C compiled library via ctypes. Is it possible to call this ctypes defined / imported library from wasm using this library?

### Additional details

In my usecase, we have a lot of numerical code from C++/C wrapped exposed to python. To speed up the execution, it would be great to move some of the code from python to wasm. For prototype reasons, writing a first version in python is preferred.

The closest I could find is issue #28. However, this is not about importing python but native code, where the (ctypes) are assumed to be known.

**Comment by Mec-iS** [comment]
I suppose a better approach is to [compile directly your C library](https://developer.mozilla.org/en-US/docs/WebAssembly/existing_C_to_wasm) into Wasm binary and export the functions you need. [Python scientific stack](https://github.com/iodide-project/pyodide) has been successfully used as Wasm modules; I suppose your needs are similar.

On the case of moving some Python functions into Wasm, it is a good idea depending on their characteristics; to do it implies porting your Python functions into a language that compiles to Wasm (check [my posts](https://dev.to/tuned/rust-scales-python-basic-experiment-49h0) to find some examples).

**Comment by jviereck** [comment]
Thanks for the reply and links! In our case we control real hardware from C running rtpreempt real-time threads, so we cannot compile the entire c library to wasm.

Am 9. Oktober 2019 07:59:10 GMT-04:00 schrieb Lorenzo <notifications@github.com>:

**Comment by Hywan** [comment]
Hello,

I think it's fine to just declare these functions as imports on the Wasm side, and links them in the Python land. Unfortunately, the `python-ext-wasm` project doesn't support Wasm imports yet. I'm working on it since 2 weeks, when I've time. It will land as soon as possible :-).

**Comment by Hywan** [comment]
Closing since there is nothing more to do. Subscribe to #28 to learn when host functions will be supported.
