### ISSUE TITLE
Example/greet.py doesn't work well

### ISSUE THREAD

**Issue by d0iasm** [wasmerio/python-ext-wasm#94]
Example/greet.py doesn't work well.

# Describe
Executing example/greet.py fails with the following message.
```
$ python examples/greet.py
Traceback (most recent call last):
  File "examples/greet.py", line 19, in <module>
    memory[0:length_of_subject] = subject
TypeError: 'slice' object cannot be interpreted as an integer
```

If I modify the part `memory[0:length_of_subject] = subject` to the following code, it works well. 
```
for i in range(length_of_subject-1):
  memory[i] = subject[i]
```
However, slice assignment should work well based on the implementation `__setitem__` in `impl PyMappingProtocol for Uint8Array`.

I'm not sure if it relates to this issue but I found the external issue (https://github.com/PyO3/pyo3/issues/611).

**Comment by Hywan** [comment]
How did you install the project? I'm not able to reproduce with `master`.

**Comment by Mec-iS** [comment]
I can confirm the problem.

I had a quick look into this and there is an hint of the possible solution in [this answer](https://stackoverflow.com/a/29293021/2536357). It seems that `__setitem__` should consider the particular case of when a slice is passed.

I currently work-around with this implementation:
```python
...
# Allocate memory for the subject, and get a pointer to it.
input_pointer = instance.exports.allocate(length_of_subject)

# Write the subject into the memory.
def write_to_view(bytestr, mem_view, offset=0):
    """Fill memory with values from a bytestring starting at `offset`"""
    for i, c in enumerate(bytestr):
        mem_view[offset + i] = c
    return mem_view

memory = instance.memory.uint8_view(input_pointer)
memory = write_to_view(subject, memory)
...
```

**Comment by Mec-iS** [comment]
e5fa143ca8fd577588e077685538e9c5d12957fe fixed for me

**Comment by syrusakbary** [comment]
Awesome, let us know @d0iasm if that fixes the issue :)

**Comment by Hywan** [comment]
What Rust version do you have?

**Comment by d0iasm** [comment]
It works well now! I pulled https://github.com/wasmerio/python-ext-wasm/commit/e5fa143ca8fd577588e077685538e9c5d12957fe, and set up via `just prelude` again.
Thank you! I'll close this issue.
